### ISSUE TITLE
Update description to render as html

### ISSUE THREAD

**Issue by jacpete** [trevinflick/ArtPOD#3]
It looks like the description is being rendered as text, but may come from the source with HTML formatting

https://github.com/trevinflick/ArtPOD/blob/1b3d8699a4d284a26b6079aa940805025f7a67e2/app.py#L51-L54

https://github.com/trevinflick/ArtPOD/blob/1b3d8699a4d284a26b6079aa940805025f7a67e2/app.py#L112-L116

EX:
![image](https://github.com/user-attachments/assets/ff9e9365-0269-4635-bd98-59ecbdba297d)

You could update this so that the output is rendered as HTML as described at https://shiny.posit.co/py/docs/ui-html.html
```r
from shiny import ui
ui.HTML("<p>Hello <strong>world</strong>!</p>")
```
similar to how you are doing the artist name
https://github.com/trevinflick/ArtPOD/blob/1b3d8699a4d284a26b6079aa940805025f7a67e2/app.py#L122

**Comment by trevinflick** [comment]
Good catch! Thanks for the assistance. I noticed the <em>tesserae</em> but wasn't sure of a fix right away. I think 6bcd05dbfed6be4a8a6da00d54f1ecb22440deea should fix this so the description renders HTML in the future.
